import type { Player, PlayerAttributes, Position, Squad } from "./types";

// [shirt, name, positions, rating, overrides?]
// Attributes come from the primary-position archetype below; override only
// where a player was genuinely unusual for their role.
type PlayerSeed = [number, string, string, number] | [number, string, string, number, Partial<PlayerAttributes>];

type Archetype = { attack: number; defense: number; passing: number; physical: number };

const archetypes: Record<Position, Archetype> = {
  GK: { attack: -68, defense: 3, passing: -16, physical: -7 },
  CB: { attack: -45, defense: 2, passing: -12, physical: -1 },
  RB: { attack: -20, defense: -1, passing: -7, physical: -5 },
  LB: { attack: -20, defense: -1, passing: -7, physical: -5 },
  RWB: { attack: -13, defense: -7, passing: -6, physical: -3 },
  LWB: { attack: -13, defense: -7, passing: -6, physical: -3 },
  CDM: { attack: -26, defense: 1, passing: -4, physical: -1 },
  CM: { attack: -13, defense: -9, passing: 3, physical: -6 },
  CAM: { attack: -3, defense: -25, passing: 4, physical: -11 },
  RM: { attack: -7, defense: -16, passing: -1, physical: -8 },
  LM: { attack: -7, defense: -16, passing: -1, physical: -8 },
  RW: { attack: 2, defense: -31, passing: -5, physical: -10 },
  LW: { attack: 2, defense: -31, passing: -5, physical: -10 },
  ST: { attack: 4, defense: -37, passing: -12, physical: -3 },
};

function clamp(value: number) {
  return Math.max(8, Math.min(99, Math.round(value)));
}

function slugify(value: string) {
  return value
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function squad(
  id: string,
  nation: string,
  code: string,
  flag: string,
  year: number,
  seeds: PlayerSeed[],
): Squad {
  const players: Player[] = seeds.map(([number, name, positionList, rating, overrides]) => {
    const positions = positionList.split("/") as Position[];
    const archetype = archetypes[positions[0]];

    return {
      id: `${id}-${slugify(name)}-${number}`,
      number,
      name,
      positions,
      rating,
      attack: clamp(overrides?.attack ?? rating + archetype.attack),
      defense: clamp(overrides?.defense ?? rating + archetype.defense),
      passing: clamp(overrides?.passing ?? rating + archetype.passing),
      physical: clamp(overrides?.physical ?? rating + archetype.physical),
    };
  });

  return { id, nation, code, flag, year, players };
}

export const squads: Squad[] = [
  squad("bra-1970", "Brazil", "BRA", "🇧🇷", 1970, [
    [1, "Félix", "GK", 79],
    [22, "Leão", "GK", 81],
    [4, "Carlos Alberto", "RB", 90, { passing: 84 }],
    [2, "Brito", "CB", 82],
    [3, "Piazza", "CB/CDM", 85],
    [6, "Everaldo", "LB", 80],
    [13, "Zé Maria", "RB", 79],
    [14, "Joel Camargo", "CB", 78],
    [16, "Marco Antônio", "LB", 77],
    [5, "Clodoaldo", "CDM/CM", 86],
    [8, "Gérson", "CM", 90, { passing: 95 }],
    [18, "Edu", "LW/LM", 82],
    [15, "Paulo Cézar Caju", "LW/CAM", 83],
    [17, "Baldocchi", "CB", 75],
    [7, "Jairzinho", "RW", 91],
    [9, "Tostão", "ST/CAM", 89],
    [10, "Pelé", "CAM/ST", 98, { passing: 95, attack: 98 }],
    [11, "Rivelino", "LM/CAM", 90, { passing: 91 }],
  ]),

  squad("ger-1974", "West Germany", "FRG", "🇩🇪", 1974, [
    [1, "Sepp Maier", "GK", 88],
    [22, "Wolfgang Kleff", "GK", 76],
    [2, "Berti Vogts", "RB", 86],
    [5, "Franz Beckenbauer", "CB", 95, { passing: 92, attack: 66 }],
    [4, "Hans-Georg Schwarzenbeck", "CB", 82],
    [3, "Paul Breitner", "LB/CM", 88, { attack: 74 }],
    [19, "Horst-Dieter Höttges", "RB/CB", 77],
    [15, "Bernard Dietz", "LB", 76],
    [6, "Herbert Wimmer", "CM", 81],
    [7, "Rainer Bonhof", "CM/CDM", 85],
    [8, "Bernd Cullmann", "CM/RM", 80],
    [18, "Wolfgang Overath", "CM/CAM", 88, { passing: 90 }],
    [10, "Günter Netzer", "CAM", 88, { passing: 92 }],
    [12, "Heinz Flohe", "CM", 79],
    [9, "Jürgen Grabowski", "RW/RM", 85],
    [11, "Jupp Heynckes", "ST/LW", 85],
    [13, "Gerd Müller", "ST", 93, { attack: 97 }],
    [14, "Uli Hoeneß", "RW/CM", 86],
  ]),

  squad("ned-1974", "Netherlands", "NED", "🇳🇱", 1974, [
    [1, "Jan Jongbloed", "GK", 78],
    [8, "Piet Schrijvers", "GK", 76],
    [2, "Wim Suurbier", "RB", 84],
    [3, "Wim Rijsbergen", "CB", 81],
    [13, "Rinus Israël", "CB", 82],
    [5, "Ruud Krol", "LB/CB", 89],
    [15, "Pleun Strik", "CB/CM", 76],
    [22, "Willy van de Kerkhof", "CM/RM", 82],
    [4, "Arie Haan", "CM/CB", 86],
    [6, "Wim Jansen", "CM/CDM", 83],
    [7, "Johan Neeskens", "CM", 91, { physical: 88 }],
    [16, "Wim van Hanegem", "CM/CAM", 89, { passing: 93 }],
    [21, "René van de Kerkhof", "RM/RW", 82],
    [17, "Piet Keizer", "LW", 84],
    [14, "Johan Cruyff", "CAM/ST", 97, { passing: 95, attack: 96 }],
    [12, "Rob Rensenbrink", "LW", 88],
    [11, "Johnny Rep", "RW/ST", 86],
    [20, "Ruud Geels", "ST", 81],
  ]),

  squad("arg-1978", "Argentina", "ARG", "🇦🇷", 1978, [
    [5, "Ubaldo Fillol", "GK", 88],
    [3, "Héctor Baley", "GK", 74],
    [14, "Jorge Olguín", "RB", 80],
    [7, "Luis Galván", "CB", 81],
    [18, "Daniel Passarella", "CB", 89, { attack: 62 }],
    [19, "Osvaldo Piazza", "CB", 80],
    [20, "Alberto Tarantini", "LB", 82],
    [16, "Miguel Oviedo", "LB/CB", 75],
    [8, "Rubén Galván", "CDM", 76],
    [6, "Américo Gallego", "CDM/CM", 84],
    [2, "Osvaldo Ardiles", "CM/CAM", 88, { passing: 89 }],
    [1, "Norberto Alonso", "CAM", 83],
    [12, "Omar Larrosa", "CM", 78],
    [21, "Ricardo Villa", "CM", 80],
    [10, "Mario Kempes", "ST/CAM", 91, { attack: 93 }],
    [4, "Daniel Bertoni", "RW", 85],
    [9, "René Houseman", "RW/LW", 84],
    [13, "Leopoldo Luque", "ST", 86],
    [15, "Oscar Ortiz", "LW", 79],
  ]),

  squad("ita-1982", "Italy", "ITA", "🇮🇹", 1982, [
    [1, "Dino Zoff", "GK", 90],
    [12, "Ivano Bordon", "GK", 76],
    [2, "Giuseppe Bergomi", "RB/CB", 84],
    [5, "Fulvio Collovati", "CB", 82],
    [6, "Claudio Gentile", "CB/RB", 87, { physical: 92 }],
    [7, "Gaetano Scirea", "CB", 90, { passing: 84 }],
    [3, "Antonio Cabrini", "LB", 86],
    [13, "Giuseppe Baresi", "CDM", 79],
    [14, "Marco Tardelli", "CM", 88],
    [10, "Giancarlo Antognoni", "CAM", 87, { passing: 90 }],
    [4, "Gabriele Oriali", "CDM/CM", 82],
    [16, "Bruno Conti", "RW/RM", 87],
    [9, "Alessandro Altobelli", "ST", 84],
    [20, "Paolo Rossi", "ST", 88, { attack: 92 }],
    [19, "Francesco Graziani", "ST", 81],
    [15, "Franco Causio", "RM/RW", 82],
    [11, "Giampiero Marini", "CM", 77],
    [8, "Pietro Vierchowod", "CB", 83],
  ]),

  squad("bra-1982", "Brazil", "BRA", "🇧🇷", 1982, [
    [1, "Waldir Peres", "GK", 76],
    [12, "Paulo Sérgio", "GK", 74],
    [2, "Leandro", "RB", 87],
    [3, "Oscar", "CB", 83],
    [4, "Luizinho", "CB", 82],
    [6, "Júnior", "LB/LM", 88, { attack: 76 }],
    [13, "Edevaldo", "RB", 76],
    [14, "Pedrinho", "LB", 74],
    [5, "Toninho Cerezo", "CM", 87],
    [8, "Sócrates", "CM/CAM", 92, { passing: 94 }],
    [15, "Falcão", "CM/CAM", 91, { passing: 92 }],
    [17, "Batista", "CDM", 79],
    [10, "Zico", "CAM", 94, { passing: 94, attack: 92 }],
    [7, "Éder", "LW/LM", 87],
    [11, "Dirceu", "LM/CAM", 82],
    [9, "Serginho", "ST", 78],
    [18, "Roberto Dinamite", "ST", 84],
    [20, "Paulo Isidoro", "RW", 80],
  ]),

  squad("fra-1982", "France", "FRA", "🇫🇷", 1982, [
    [1, "Jean-Luc Ettori", "GK", 74],
    [22, "Jean Castaneda", "GK", 73],
    [2, "Manuel Amoros", "RB", 84],
    [5, "Marius Trésor", "CB", 86],
    [8, "Christian Lopez", "CB", 80],
    [3, "Maxime Bossis", "LB/CB", 85],
    [15, "Gérard Janvion", "RB", 78],
    [4, "Jean-François Larios", "CM", 80],
    [6, "Alain Giresse", "CM/CAM", 89, { passing: 90 }],
    [12, "Jean Tigana", "CM", 87],
    [10, "Michel Platini", "CAM", 94, { passing: 95, attack: 91 }],
    [14, "Bernard Genghini", "CM/CAM", 82],
    [17, "Dominique Bathenay", "CDM", 78],
    [9, "Bernard Lacombe", "ST", 82],
    [11, "Didier Six", "LW", 81],
    [18, "Dominique Rocheteau", "RW/ST", 85],
    [20, "Alain Couriol", "RW", 78],
    [7, "Gérard Soler", "ST", 77],
  ]),

  squad("arg-1986", "Argentina", "ARG", "🇦🇷", 1986, [
    [18, "Nery Pumpido", "GK", 84],
    [15, "Luis Islas", "GK", 74],
    [9, "José Luis Cuciuffo", "RB/CB", 80],
    [19, "Oscar Ruggeri", "CB", 87],
    [5, "José Luis Brown", "CB", 82],
    [6, "Daniel Passarella", "CB", 86],
    [8, "Néstor Clausen", "RB", 78],
    [13, "Oscar Garré", "LB", 78],
    [16, "Julio Olarticoechea", "LB", 80],
    [2, "Sergio Batista", "CDM", 83],
    [14, "Ricardo Giusti", "CM/RM", 82],
    [22, "Héctor Enrique", "CM", 80],
    [20, "Carlos Tapia", "CM/CAM", 78],
    [10, "Diego Maradona", "CAM/ST", 99, { passing: 96, attack: 98, physical: 88 }],
    [7, "Jorge Burruchaga", "RW/CAM", 87],
    [11, "Jorge Valdano", "ST", 86],
    [4, "Claudio Borghi", "CAM/LW", 82],
    [17, "Pedro Pasculli", "ST", 78],
  ]),

  squad("ger-1990", "West Germany", "FRG", "🇩🇪", 1990, [
    [1, "Bodo Illgner", "GK", 86],
    [12, "Raimond Aumann", "GK", 76],
    [2, "Stefan Reuter", "RB/RM", 83],
    [4, "Jürgen Kohler", "CB", 88],
    [5, "Klaus Augenthaler", "CB", 85],
    [6, "Guido Buchwald", "CB/CDM", 84],
    [3, "Andreas Brehme", "LB", 88, { passing: 85 }],
    [14, "Thomas Berthold", "RB/CB", 81],
    [8, "Thomas Häßler", "RM/CAM", 86],
    [10, "Lothar Matthäus", "CM", 93, { attack: 84, passing: 88 }],
    [7, "Pierre Littbarski", "RW/RM", 85],
    [16, "Olaf Thon", "CM/CAM", 82],
    [15, "Uwe Bein", "CAM", 81],
    [9, "Rudi Völler", "ST", 88],
    [18, "Jürgen Klinsmann", "ST", 89],
    [11, "Karl-Heinz Riedle", "ST", 83],
    [17, "Frank Mill", "ST/RW", 78],
    [13, "Karlheinz Förster", "CB", 80],
  ]),

  squad("cmr-1990", "Cameroon", "CMR", "🇨🇲", 1990, [
    [1, "Thomas N'Kono", "GK", 84],
    [16, "Joseph-Antoine Bell", "GK", 82],
    [2, "Stephen Tataw", "RB", 78],
    [5, "Jules Onana", "CB", 78],
    [4, "Benjamin Massing", "CB", 77, { physical: 84 }],
    [3, "Victor N'Dip", "LB/CB", 75],
    [12, "Bertin Ebwelle", "RB", 73],
    [6, "Emile Mbouh", "CDM", 77],
    [8, "André Kana-Biyik", "CDM/CB", 78],
    [10, "Cyrille Makanaky", "CAM/LW", 82],
    [7, "Emmanuel Kundé", "CM/CB", 80],
    [15, "Thomas Libiih", "CM", 74],
    [11, "Eugène Ekéké", "ST/CAM", 79],
    [14, "Louis-Paul M'Fédé", "CAM", 79],
    [9, "François Omam-Biyik", "ST", 83],
    [17, "Bonaventure Djonkep", "LW", 74],
    [18, "Cyrille Tollo", "RM", 73],
    [13, "Roger Milla", "ST", 85, { attack: 88 }],
  ]),

  squad("eng-1990", "England", "ENG", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", 1990, [
    [1, "Peter Shilton", "GK", 88],
    [13, "Chris Woods", "GK", 78],
    [2, "Gary Stevens", "RB", 79],
    [6, "Terry Butcher", "CB", 84],
    [5, "Des Walker", "CB", 86],
    [14, "Mark Wright", "CB", 83],
    [3, "Stuart Pearce", "LB", 86, { physical: 88 }],
    [12, "Paul Parker", "RB/CB", 82],
    [4, "Neil Webb", "CM", 79],
    [8, "Chris Waddle", "LW/LM", 86],
    [7, "David Platt", "CM/CAM", 84],
    [16, "Steve McMahon", "CDM", 80],
    [19, "Paul Gascoigne", "CAM", 90, { passing: 92 }],
    [11, "John Barnes", "LW", 87],
    [10, "Gary Lineker", "ST", 89, { attack: 92 }],
    [9, "Peter Beardsley", "CAM/ST", 84],
    [20, "Steve Bull", "ST", 76],
    [18, "Trevor Steven", "RM", 79],
  ]),

  squad("bra-1994", "Brazil", "BRA", "🇧🇷", 1994, [
    [1, "Cláudio Taffarel", "GK", 85],
    [12, "Zetti", "GK", 77],
    [2, "Jorginho", "RB", 82],
    [4, "Aldair", "CB", 87],
    [3, "Márcio Santos", "CB", 82],
    [6, "Branco", "LB", 83],
    [14, "Cafu", "RB", 85],
    [13, "Leonardo", "LB/LM", 84],
    [5, "Mauro Silva", "CDM", 85],
    [8, "Dunga", "CDM/CM", 86],
    [15, "Mazinho", "CM/RM", 80],
    [17, "Zinho", "LM/CAM", 82],
    [10, "Raí", "CAM", 85],
    [20, "Müller", "RW/ST", 80],
    [9, "Bebeto", "ST", 88],
    [11, "Romário", "ST", 93, { attack: 96 }],
    [21, "Viola", "ST/RW", 78],
    [18, "Paulo Sérgio", "LW", 79],
  ]),

  squad("fra-1998", "France", "FRA", "🇫🇷", 1998, [
    [16, "Fabien Barthez", "GK", 87],
    [1, "Bernard Lama", "GK", 80],
    [15, "Lilian Thuram", "RB/CB", 89],
    [8, "Marcel Desailly", "CB", 90],
    [5, "Laurent Blanc", "CB", 88, { passing: 84 }],
    [3, "Bixente Lizarazu", "LB", 86],
    [18, "Frank Lebœuf", "CB", 83],
    [19, "Christian Karembeu", "CM/RB", 82],
    [7, "Didier Deschamps", "CDM", 86],
    [17, "Emmanuel Petit", "CM", 86],
    [4, "Patrick Vieira", "CM/CDM", 85],
    [10, "Zinedine Zidane", "CAM", 96, { passing: 97, attack: 92 }],
    [6, "Youri Djorkaeff", "CAM/RW", 87],
    [11, "Robert Pirès", "LM/LW", 83],
    [14, "Alain Boghossian", "CM", 78],
    [12, "Thierry Henry", "LW/ST", 88],
    [9, "Stéphane Guivarc'h", "ST", 76],
    [20, "David Trezeguet", "ST", 84],
  ]),

  squad("bra-1998", "Brazil", "BRA", "🇧🇷", 1998, [
    [1, "Cláudio Taffarel", "GK", 85],
    [12, "Dida", "GK", 80],
    [2, "Cafu", "RB", 90],
    [3, "Aldair", "CB", 87],
    [4, "Júnior Baiano", "CB", 80],
    [6, "Roberto Carlos", "LB", 90, { attack: 82 }],
    [13, "Zé Carlos", "RB", 76],
    [14, "Gonçalves", "CB", 78],
    [5, "César Sampaio", "CDM", 82],
    [8, "Dunga", "CDM/CM", 85],
    [15, "Leonardo", "CAM/LM", 85],
    [17, "Doriva", "CDM", 76],
    [10, "Rivaldo", "CAM/LW", 92, { passing: 90 }],
    [11, "Emerson", "CM", 82],
    [18, "Denílson", "LW", 82],
    [7, "Giovanni", "CAM", 80],
    [9, "Ronaldo", "ST", 95, { attack: 97, physical: 89 }],
    [20, "Bebeto", "ST", 84],
  ]),

  squad("bra-2002", "Brazil", "BRA", "🇧🇷", 2002, [
    [1, "Marcos", "GK", 85],
    [12, "Dida", "GK", 83],
    [2, "Cafu", "RB", 90],
    [3, "Lúcio", "CB", 88],
    [4, "Roque Júnior", "CB", 82],
    [5, "Edmílson", "CB/CDM", 84],
    [6, "Roberto Carlos", "LB", 91, { attack: 84 }],
    [13, "Belletti", "RB", 81],
    [16, "Júnior", "LB", 79],
    [8, "Gilberto Silva", "CDM", 84],
    [15, "Kléberson", "CM", 82],
    [17, "Denílson", "LW", 80],
    [19, "Juninho Paulista", "CAM", 82],
    [10, "Rivaldo", "CAM/LW", 92],
    [11, "Ronaldinho", "LW/CAM", 93, { passing: 93 }],
    [7, "Ricardinho", "CM", 78],
    [9, "Ronaldo", "ST", 95, { attack: 97 }],
    [21, "Luizão", "ST", 79],
  ]),

  squad("kor-2002", "South Korea", "KOR", "🇰🇷", 2002, [
    [1, "Lee Woon-jae", "GK", 82],
    [12, "Choi Eun-sung", "GK", 76],
    [22, "Song Chong-gug", "RB/RM", 79],
    [20, "Hong Myung-bo", "CB", 85, { passing: 82 }],
    [4, "Choi Jin-cheul", "CB", 80],
    [2, "Kim Tae-young", "CB", 79],
    [3, "Lee Min-sung", "LB/CB", 77],
    [10, "Lee Young-pyo", "LB/LM", 82],
    [5, "Kim Nam-il", "CDM", 81],
    [6, "Yoo Sang-chul", "CM/CDM", 82],
    [21, "Park Ji-sung", "CM/LM", 85],
    [13, "Lee Eul-yong", "LM/CAM", 78],
    [8, "Choi Tae-uk", "RM/ST", 77],
    [16, "Cha Du-ri", "RM/ST", 76],
    [14, "Lee Chun-soo", "LW/CAM", 80],
    [15, "Seol Ki-hyeon", "RW/ST", 81],
    [19, "Ahn Jung-hwan", "ST/CAM", 83],
    [18, "Hwang Sun-hong", "ST", 80],
  ]),

  squad("ita-2006", "Italy", "ITA", "🇮🇹", 2006, [
    [1, "Gianluigi Buffon", "GK", 93],
    [12, "Angelo Peruzzi", "GK", 81],
    [19, "Gianluca Zambrotta", "RB/LB", 88],
    [5, "Fabio Cannavaro", "CB", 93],
    [13, "Alessandro Nesta", "CB", 91],
    [23, "Marco Materazzi", "CB", 84],
    [3, "Fabio Grosso", "LB", 84],
    [2, "Cristian Zaccardo", "RB/CB", 78],
    [4, "Daniele De Rossi", "CM/CDM", 85],
    [8, "Gennaro Gattuso", "CDM", 86, { physical: 90 }],
    [21, "Andrea Pirlo", "CM/CDM", 92, { passing: 96 }],
    [16, "Mauro Camoranesi", "RM/RW", 84],
    [20, "Simone Perrotta", "CM", 81],
    [10, "Francesco Totti", "CAM", 90, { passing: 92 }],
    [15, "Vincenzo Iaquinta", "ST", 79],
    [7, "Alessandro Del Piero", "CAM/ST", 89],
    [9, "Luca Toni", "ST", 86],
    [11, "Alberto Gilardino", "ST", 82],
  ]),

  squad("por-2006", "Portugal", "POR", "🇵🇹", 2006, [
    [1, "Ricardo", "GK", 84],
    [12, "Quim", "GK", 77],
    [13, "Miguel", "RB", 82],
    [16, "Ricardo Carvalho", "CB", 87],
    [5, "Fernando Meira", "CB", 81],
    [2, "Paulo Ferreira", "RB/CB", 82],
    [14, "Nuno Valente", "LB", 79],
    [3, "Caneira", "CB/LB", 76],
    [6, "Costinha", "CDM", 82],
    [18, "Maniche", "CM", 85],
    [8, "Petit", "CDM/CM", 80],
    [19, "Tiago", "CM", 82],
    [10, "Rui Costa", "CAM", 87, { passing: 91 }],
    [20, "Deco", "CAM/CM", 89, { passing: 92 }],
    [7, "Luís Figo", "RW/RM", 89],
    [17, "Cristiano Ronaldo", "RW/LW", 86],
    [11, "Simão", "LW/LM", 84],
    [9, "Pauleta", "ST", 84],
  ]),

  squad("esp-2010", "Spain", "ESP", "🇪🇸", 2010, [
    [1, "Iker Casillas", "GK", 92],
    [23, "Pepe Reina", "GK", 84],
    [15, "Sergio Ramos", "RB/CB", 89],
    [3, "Gerard Piqué", "CB", 88],
    [5, "Carles Puyol", "CB", 89],
    [11, "Joan Capdevila", "LB", 82],
    [17, "Álvaro Arbeloa", "RB", 80],
    [2, "Raúl Albiol", "CB", 79],
    [16, "Sergio Busquets", "CDM", 87],
    [14, "Xabi Alonso", "CM/CDM", 88, { passing: 92 }],
    [8, "Xavi", "CM/CAM", 93, { passing: 97 }],
    [6, "Andrés Iniesta", "CAM/LM", 93, { passing: 94 }],
    [10, "Cesc Fàbregas", "CM/CAM", 86],
    [21, "David Silva", "CAM/RW", 87],
    [22, "Jesús Navas", "RW/RM", 82],
    [7, "David Villa", "ST/LW", 90, { attack: 93 }],
    [9, "Fernando Torres", "ST", 85],
    [18, "Pedro", "RW/LW", 83],
  ]),

  squad("ned-2010", "Netherlands", "NED", "🇳🇱", 2010, [
    [1, "Maarten Stekelenburg", "GK", 84],
    [16, "Michel Vorm", "GK", 79],
    [2, "Gregory van der Wiel", "RB", 81],
    [3, "John Heitinga", "CB", 82],
    [4, "Joris Mathijsen", "CB", 82],
    [5, "Giovanni van Bronckhorst", "LB", 84],
    [13, "André Ooijer", "CB", 78],
    [12, "Khalid Boulahrouz", "RB/CB", 77],
    [6, "Mark van Bommel", "CDM", 84],
    [8, "Nigel de Jong", "CDM", 82],
    [20, "Ibrahim Afellay", "CM/RW", 81],
    [14, "Demy de Zeeuw", "CM", 78],
    [10, "Wesley Sneijder", "CAM", 90, { passing: 91 }],
    [7, "Dirk Kuyt", "RW/ST", 83],
    [11, "Arjen Robben", "RW", 91],
    [23, "Rafael van der Vaart", "CAM", 84],
    [9, "Robin van Persie", "ST", 88],
    [17, "Eljero Elia", "LW", 79],
  ]),

  squad("uru-2010", "Uruguay", "URU", "🇺🇾", 2010, [
    [1, "Fernando Muslera", "GK", 83],
    [12, "Juan Castillo", "GK", 75],
    [16, "Maxi Pereira", "RB", 82],
    [2, "Diego Lugano", "CB", 83],
    [3, "Diego Godín", "CB", 86],
    [4, "Jorge Fucile", "LB/RB", 79],
    [22, "Martín Cáceres", "CB/RB", 81],
    [19, "Andrés Scotti", "CB", 76],
    [15, "Diego Pérez", "CDM", 80],
    [17, "Egidio Arévalo Ríos", "CDM", 81],
    [6, "Mauricio Victorino", "CB", 77],
    [11, "Álvaro Pereira", "LM/LB", 81],
    [7, "Nicolás Lodeiro", "CAM/LM", 79],
    [20, "Álvaro Fernández", "LM/CAM", 78],
    [8, "Sebastián Eguren", "CM", 76],
    [10, "Diego Forlán", "ST/CAM", 89, { attack: 91 }],
    [9, "Luis Suárez", "ST", 88],
    [13, "Sebastián Abreu", "ST", 76],
  ]),

  squad("ger-2014", "Germany", "GER", "🇩🇪", 2014, [
    [1, "Manuel Neuer", "GK", 93],
    [12, "Ron-Robert Zieler", "GK", 78],
    [16, "Philipp Lahm", "RB/CM", 90],
    [20, "Jérôme Boateng", "CB", 87],
    [5, "Mats Hummels", "CB", 88, { passing: 84 }],
    [4, "Benedikt Höwedes", "CB/LB", 82],
    [17, "Per Mertesacker", "CB", 83],
    [15, "Erik Durm", "LB", 75],
    [6, "Sami Khedira", "CM", 85],
    [7, "Bastian Schweinsteiger", "CM/CDM", 89],
    [18, "Toni Kroos", "CM", 91, { passing: 95 }],
    [8, "Mesut Özil", "CAM/LM", 88, { passing: 92 }],
    [23, "Christoph Kramer", "CDM", 77],
    [19, "Mario Götze", "CAM/LW", 85],
    [13, "Thomas Müller", "RW/ST", 89],
    [11, "Miroslav Klose", "ST", 85, { attack: 89 }],
    [9, "André Schürrle", "LW/ST", 83],
    [10, "Lukas Podolski", "LW", 81],
  ]),

  squad("fra-2018", "France", "FRA", "🇫🇷", 2018, [
    [1, "Hugo Lloris", "GK", 88],
    [16, "Steve Mandanda", "GK", 81],
    [2, "Benjamin Pavard", "RB/CB", 82],
    [4, "Raphaël Varane", "CB", 89],
    [5, "Samuel Umtiti", "CB", 85],
    [21, "Lucas Hernández", "LB/CB", 84],
    [3, "Presnel Kimpembe", "CB", 80],
    [17, "Adil Rami", "CB", 79],
    [13, "N'Golo Kanté", "CDM", 90, { defense: 92 }],
    [6, "Paul Pogba", "CM", 88, { passing: 89 }],
    [14, "Blaise Matuidi", "CM/LM", 83],
    [15, "Steven Nzonzi", "CDM", 79],
    [8, "Thomas Lemar", "LM/CAM", 81],
    [7, "Antoine Griezmann", "CAM/ST", 90],
    [10, "Kylian Mbappé", "RW/ST", 91, { attack: 93, physical: 87 }],
    [11, "Ousmane Dembélé", "RW/LW", 82],
    [9, "Olivier Giroud", "ST", 83],
    [20, "Florian Thauvin", "RW", 80],
  ]),

  squad("cro-2018", "Croatia", "CRO", "🇭🇷", 2018, [
    [23, "Danijel Subašić", "GK", 83],
    [12, "Lovre Kalinić", "GK", 76],
    [2, "Šime Vrsaljko", "RB", 82],
    [6, "Dejan Lovren", "CB", 83],
    [21, "Domagoj Vida", "CB", 82],
    [3, "Ivan Strinić", "LB", 78],
    [5, "Vedran Ćorluka", "CB", 78],
    [22, "Josip Pivarić", "LB", 75],
    [11, "Marcelo Brozović", "CDM/CM", 84],
    [7, "Ivan Rakitić", "CM", 87, { passing: 89 }],
    [10, "Luka Modrić", "CM/CAM", 92, { passing: 95 }],
    [8, "Mateo Kovačić", "CM", 82],
    [19, "Milan Badelj", "CDM", 79],
    [4, "Ivan Perišić", "LW/LM", 86],
    [18, "Ante Rebić", "RW/ST", 82],
    [20, "Marko Pjaca", "LW", 78],
    [17, "Mario Mandžukić", "ST", 85],
    [9, "Andrej Kramarić", "ST/CAM", 81],
  ]),

  squad("bel-2018", "Belgium", "BEL", "🇧🇪", 2018, [
    [1, "Thibaut Courtois", "GK", 90],
    [12, "Simon Mignolet", "GK", 79],
    [2, "Toby Alderweireld", "CB", 87],
    [5, "Jan Vertonghen", "CB/LB", 86],
    [4, "Vincent Kompany", "CB", 86],
    [15, "Thomas Meunier", "RB/RWB", 82],
    [21, "Timothy Castagne", "RWB/RB", 79],
    [3, "Thomas Vermaelen", "CB", 79],
    [6, "Axel Witsel", "CDM", 85],
    [8, "Marouane Fellaini", "CM", 81],
    [19, "Mousa Dembélé", "CM", 83],
    [22, "Nacer Chadli", "LM/LWB", 79],
    [7, "Kevin De Bruyne", "CM/CAM", 92, { passing: 95 }],
    [10, "Eden Hazard", "LW/CAM", 91],
    [11, "Yannick Carrasco", "LW/LM", 82],
    [14, "Dries Mertens", "RW/ST", 84],
    [9, "Romelu Lukaku", "ST", 87],
    [17, "Youri Tielemans", "CM", 80],
  ]),

  squad("arg-2022", "Argentina", "ARG", "🇦🇷", 2022, [
    [23, "Emiliano Martínez", "GK", 87],
    [12, "Gerónimo Rulli", "GK", 78],
    [4, "Gonzalo Montiel", "RB", 79],
    [26, "Nahuel Molina", "RB", 81],
    [13, "Cristian Romero", "CB", 85],
    [19, "Nicolás Otamendi", "CB", 83],
    [25, "Lisandro Martínez", "CB", 84],
    [3, "Nicolás Tagliafico", "LB", 81],
    [8, "Marcos Acuña", "LB/LWB", 82],
    [5, "Leandro Paredes", "CDM", 81],
    [7, "Rodrigo De Paul", "CM", 84],
    [24, "Enzo Fernández", "CM", 85],
    [20, "Alexis Mac Allister", "CM/CAM", 84],
    [11, "Ángel Di María", "RW/LW", 87],
    [10, "Lionel Messi", "CAM/RW", 96, { passing: 95, attack: 96 }],
    [22, "Lautaro Martínez", "ST", 84],
    [9, "Julián Álvarez", "ST", 84],
    [21, "Paulo Dybala", "CAM/ST", 83],
  ]),

  squad("mar-2022", "Morocco", "MAR", "🇲🇦", 2022, [
    [1, "Yassine Bounou", "GK", 87],
    [12, "Munir Mohamedi", "GK", 76],
    [2, "Achraf Hakimi", "RB/RWB", 87],
    [5, "Nayef Aguerd", "CB", 83],
    [6, "Romain Saïss", "CB", 82],
    [3, "Noussair Mazraoui", "LB/RB", 83],
    [18, "Jawad El Yamiq", "CB", 78],
    [24, "Badr Benoun", "CB", 76],
    [4, "Sofyan Amrabat", "CDM", 85, { defense: 87 }],
    [8, "Azzedine Ounahi", "CM", 82],
    [15, "Selim Amallah", "CM/CAM", 79],
    [23, "Bilal El Khannouss", "CAM", 77],
    [7, "Hakim Ziyech", "RW/CAM", 85, { passing: 88 }],
    [17, "Sofiane Boufal", "LW", 82],
    [11, "Abdelhamid Sabiri", "CAM", 77],
    [9, "Abderrazak Hamdallah", "ST", 78],
    [19, "Youssef En-Nesyri", "ST", 81],
    [10, "Anass Zaroury", "LW", 76],
  ]),

  squad("bra-2022", "Brazil", "BRA", "🇧🇷", 2022, [
    [1, "Alisson", "GK", 90],
    [23, "Ederson", "GK", 87],
    [2, "Danilo", "RB/LB", 82],
    [4, "Marquinhos", "CB", 88],
    [3, "Thiago Silva", "CB", 86],
    [14, "Éder Militão", "CB/RB", 84],
    [6, "Alex Sandro", "LB", 81],
    [13, "Dani Alves", "RB", 78],
    [5, "Casemiro", "CDM", 88, { defense: 90 }],
    [17, "Lucas Paquetá", "CM/CAM", 83],
    [15, "Fabinho", "CDM", 84],
    [8, "Fred", "CM", 79],
    [10, "Neymar", "CAM/LW", 91, { passing: 91 }],
    [20, "Vinícius Júnior", "LW", 87],
    [7, "Raphinha", "RW", 83],
    [11, "Rodrygo", "RW/ST", 83],
    [9, "Richarlison", "ST", 83],
    [19, "Antony", "RW", 80],
  ]),

  squad("eng-2022", "England", "ENG", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", 2022, [
    [1, "Jordan Pickford", "GK", 84],
    [13, "Nick Pope", "GK", 81],
    [2, "Kyle Walker", "RB", 84],
    [5, "John Stones", "CB", 85],
    [6, "Harry Maguire", "CB", 81],
    [12, "Kieran Trippier", "RB/RWB", 82],
    [3, "Luke Shaw", "LB", 83],
    [16, "Conor Coady", "CB", 78],
    [4, "Declan Rice", "CDM", 85],
    [8, "Jordan Henderson", "CM", 80],
    [22, "Jude Bellingham", "CM/CAM", 86],
    [14, "Kalvin Phillips", "CDM", 80],
    [7, "Jack Grealish", "LW/CAM", 83],
    [20, "Phil Foden", "LW/CAM", 85],
    [11, "Marcus Rashford", "LW/ST", 84],
    [17, "Bukayo Saka", "RW", 85],
    [9, "Harry Kane", "ST", 90, { passing: 84 }],
    [26, "Raheem Sterling", "LW/RW", 83],
  ]),

  squad("esp-2026", "Spain", "ESP", "🇪🇸", 2026, [
    [1, "Unai Simón", "GK", 85],
    [23, "David Raya", "GK", 84],
    [2, "Pedro Porro", "RB/RWB", 82],
    [4, "Pau Cubarsí", "CB", 84],
    [14, "Aymeric Laporte", "CB", 83],
    [5, "Dean Huijsen", "CB", 82],
    [24, "Marc Cucurella", "LB/LWB", 83],
    [3, "Alejandro Grimaldo", "LB/LM", 83],
    [16, "Rodri", "CDM", 91, { defense: 90, passing: 89 }],
    [8, "Fabián Ruiz", "CM", 85],
    [6, "Mikel Merino", "CM", 83],
    [18, "Martín Zubimendi", "CDM", 84],
    [10, "Pedri", "CM/CAM", 89, { passing: 92 }],
    [9, "Gavi", "CM/CAM", 84],
    [19, "Lamine Yamal", "RW", 89],
    [11, "Nico Williams", "LW", 86],
    [7, "Álvaro Morata", "ST", 81],
    [17, "Mikel Oyarzabal", "ST/LW", 83],
  ]),

  squad("fra-2026", "France", "FRA", "🇫🇷", 2026, [
    [1, "Mike Maignan", "GK", 87],
    [16, "Brice Samba", "GK", 80],
    [2, "Jules Koundé", "RB/CB", 85],
    [4, "Dayot Upamecano", "CB", 85],
    [5, "William Saliba", "CB", 87],
    [3, "Théo Hernández", "LB", 84],
    [21, "Lucas Digne", "LB", 80],
    [24, "Ibrahima Konaté", "CB", 84],
    [13, "N'Golo Kanté", "CDM", 85],
    [8, "Aurélien Tchouaméni", "CDM/CM", 86],
    [14, "Adrien Rabiot", "CM", 84],
    [6, "Eduardo Camavinga", "CM", 84],
    [15, "Warren Zaïre-Emery", "CM", 82],
    [7, "Ousmane Dembélé", "RW/LW", 87],
    [10, "Kylian Mbappé", "ST/LW", 93, { attack: 95 }],
    [11, "Michael Olise", "RW/CAM", 85],
    [9, "Randal Kolo Muani", "ST", 81],
    [20, "Bradley Barcola", "LW", 82],
  ]),
];

export const datasetStats = {
  nations: new Set(squads.map((item) => item.nation)).size,
  squads: squads.length,
  players: squads.reduce((total, item) => total + item.players.length, 0),
};
